#!/usr/bin/env python3
"""Ersetzt in Anzeigetexten und Kommentaren die Ersatzschreibung ae/oe/ue/ss
durch echte Umlaute. Technische Bezeichner (CSS-Klassen, Element-IDs,
data-Attribute, JS-Schluessel, Aufzaehlungswerte) bleiben unberuehrt."""
import re, sys, os

# Reihenfolge zaehlt: laengere Woerter zuerst, damit Teilwoerter nicht stoeren.
WOERTER = [
    ("Waermeuebergangswiderstaende","Wärmeübergangswiderstände"),
    ("Uebergangswiderstaende","Übergangswiderstände"),
    ("Waermeleitfaehigkeit","Wärmeleitfähigkeit"),
    ("Plausibilitaetspruefungen","Plausibilitätsprüfungen"),
    ("Zwischensparrendaemmung","Zwischensparrendämmung"),
    ("Waermebrueckenzuschlag","Wärmebrückenzuschlag"),
    ("Waermeschutzverglasung","Wärmeschutzverglasung"),
    ("Hoehenkorrekturfaktor","Höhenkorrekturfaktor"),
    ("Abschirmkoeffizient","Abschirmkoeffizient"),
    ("Zonenverknuepfungen","Zonenverknüpfungen"),
    ("Nichtwohngebaeuden","Nichtwohngebäuden"),
    ("Bildschirmausschnitt","Bildschirmausschnitt"),
    ("Daueraufenthaltsraum","Daueraufenthaltsraum"),
    ("Grundwasserspiegel","Grundwasserspiegel"),
    ("waermeuebertragenden","wärmeübertragenden"),
    ("Vollziegelmauerwerk","Vollziegelmauerwerk"),
    ("Grundwassereinfluss","Grundwassereinfluss"),
    ("Auffaelligkeiten","Auffälligkeiten"),
    ("Holzfaserdaemmung","Holzfaserdämmung"),
    ("Gebaeudeheizlast","Gebäudeheizlast"),
    ("Wandanschluesse","Wandanschlüsse"),
    ("unberuecksichtigt","unberücksichtigt"),
    ("Waermekapazitaet","Wärmekapazität"),
    ("Aussentemperatur","Außentemperatur"),
    ("Waermestroeme","Wärmeströme"),
    ("Geschossdecke","Geschossdecke"),
    ("Waermeerzeugers","Wärmeerzeugers"),
    ("Waermeerzeuger","Wärmeerzeuger"),
    ("Gebaeudehuelle","Gebäudehülle"),
    ("Gebaeudeanteil","Gebäudeanteil"),
    ("Waermebruecke","Wärmebrücke"),
    ("Jahresschwankung","Jahresschwankung"),
    ("Erdberuehrtes","Erdberührtes"),
    ("erdberuehrte","erdberührte"),
    ("erdberuehrt","erdberührt"),
    ("Pruefhinweise","Prüfhinweise"),
    ("Quellenangabe","Quellenangabe"),
    ("Bauteilflaechen","Bauteilflächen"),
    ("Vorschlaege","Vorschläge"),
    ("Massstabslinie","Maßstabslinie"),
    ("Waermebilanz","Wärmebilanz"),
    ("Waermezufluss","Wärmezufluss"),
    ("Waermezufuhr","Wärmezufuhr"),
    ("Waermeuebergang","Wärmeübergang"),
    ("Waermestrom","Wärmestrom"),
    ("Uebergangsfall","Übergangsfall"),
    ("funktionsfaehig","funktionsfähig"),
    ("ausschliesslich","ausschließlich"),
    ("einschliesslich","einschließlich"),
    ("flaechendeckende","flächendeckende"),
    ("Kerndaemmung","Kerndämmung"),
    ("Vormauerziegel","Vormauerziegel"),
    ("Bestaetigung","Bestätigung"),
    ("Gebaeudemasse","Gebäudemasse"),
    ("Heizflaechen","Heizflächen"),
    ("Nebenraeume","Nebenräume"),
    ("Innenmasse","Innenmaße"),
    ("Huellbauteile","Hüllbauteile"),
    ("Huellbauteil","Hüllbauteil"),
    ("Huellflaeche","Hüllfläche"),
    ("Absenkdauer","Absenkdauer"),
    ("stationaeren","stationären"),
    ("stationaere","stationäre"),
    ("beruecksichtigt","berücksichtigt"),
    ("unterstuetzte","unterstützte"),
    ("uebernommenen","übernommenen"),
    ("uebernommen","übernommen"),
    ("Uebernehmen","Übernehmen"),
    ("uebernehmen","übernehmen"),
    ("Uebernahme","Übernahme"),
    ("hinzufuegen","hinzufügen"),
    ("Ausgewaehlte","Ausgewählte"),
    ("ausgewaehlt","ausgewählt"),
    ("vollstaendig","vollständig"),
    ("Vollstaendig","Vollständig"),
    ("Aussenwand","Außenwand"),
    ("Aussenluft","Außenluft"),
    ("Aussenputz","Außenputz"),
    ("Dachschraege","Dachschräge"),
    ("Pruefbarkeit","Prüfbarkeit"),
    ("geschaetzten","geschätzten"),
    ("geschaetzter","geschätzter"),
    ("geschwaerzt","geschwärzt"),
    ("unabhaengig","unabhängig"),
    ("unveraendert","unverändert"),
    ("Massbezug","Maßbezug"),
    ("MASSBEZUG","MASSBEZUG"),
    ("Masskette","Maßkette"),
    ("Massstab","Maßstab"),
    ("massgebend","maßgebend"),
    ("Daemmstoff","Dämmstoff"),
    ("gewaehlten","gewählten"),
    ("Bemessungswert","Bemessungswert"),
    ("Oberflaeche","Oberfläche"),
    ("Auflösung","Auflösung"),
    ("Aufloesung","Auflösung"),
    ("AUFLOESEN","AUFLÖSEN"),
    ("ueberfuehren","überführen"),
    ("Gebaeudes","Gebäudes"),
    ("Gebaeude","Gebäude"),
    ("Waermedurchgang","Wärmedurchgang"),
    ("WAERMEDURCHGANG","WÄRMEDURCHGANG"),
    ("Lueftungstool","Lüftungstool"),
    ("Innentuer","Innentür"),
    ("Haustuer","Haustür"),
    ("Daemmung","Dämmung"),
    ("gedaemmt","gedämmt"),
    ("ungedaemmt","ungedämmt"),
    ("Raumhoehe","Raumhöhe"),
    ("Hoehenlage","Höhenlage"),
    ("Fussboden","Fußboden"),
    ("bestaetigen","bestätigen"),
    ("bestaetigt","bestätigt"),
    ("Schliessen","Schließen"),
    ("schliessen","schließen"),
    ("schliesst","schließt"),
    ("Fassaden","Fassaden"),
    ("Flaechen","Flächen"),
    ("Flaeche","Fläche"),
    ("flaeche","fläche"),
    ("Lueftung","Lüftung"),
    ("Geschosses","Geschosses"),
    ("Geschosse","Geschosse"),
    ("Pruefraum","Prüfraum"),
    ("pruefbarer","prüfbarer"),
    ("Prueft","Prüft"),
    ("pruefen","prüfen"),
    ("geprueften","geprüften"),
    ("geprueft","geprüft"),
    ("Pruefung","Prüfung"),
    ("Messung","Messung"),
    ("Vormauer","Vormauer"),
    ("Raeumen","Räumen"),
    ("Raeume","Räume"),
    ("raeume","räume"),
    ("Kuechen","Küchen"),
    ("Kueche","Küche"),
    ("Tueren","Türen"),
    ("Laenge","Länge"),
    ("Loesung","Lösung"),
    ("Groesse","Größe"),
    ("Gelaende","Gelände"),
    ("aeusserer","äußerer"),
    ("ausserhalb","außerhalb"),
    ("Ueblicher","Üblicher"),
    ("ueblicherweise","üblicherweise"),
    ("ueblichen","üblichen"),
    ("ueblicher","üblicher"),
    ("uebliche","übliche"),
    ("uebrigen","übrigen"),
    ("uebrige","übrige"),
    ("Uebergang","Übergang"),
    ("waehlen","wählen"),
    ("auswaehlen","auswählen"),
    ("benoetigt","benötigt"),
    ("erfuellt","erfüllt"),
    ("enthaelt","enthält"),
    ("ergaenzen","ergänzen"),
    ("abstuerzen","abstürzen"),
    ("abhaengig","abhängig"),
    ("aufwaerts","aufwärts"),
    ("abwaerts","abwärts"),
    ("aehnliche","ähnliche"),
    ("auffaellig","auffällig"),
    ("ausdruecklich","ausdrücklich"),
    ("hoechste","höchste"),
    ("moeglich","möglich"),
    ("koennen","können"),
    ("muessen","müssen"),
    ("naechste","nächste"),
    ("zulaessig","zulässig"),
    ("zurueck","zurück"),
    ("Schluessel","Schlüssel"),
    ("erhoeht","erhöht"),
    ("oeffnen","öffnen"),
    ("einfuegen","einfügen"),
    ("Einfuegen","Einfügen"),
    ("Beitraege","Beiträge"),
    ("traegt","trägt"),
    ("Laeuft","Läuft"),
    ("laeuft","läuft"),
    ("Zaehlt","Zählt"),
    ("zaehlt","zählt"),
    ("loest","löst"),
    ("aelter","älter"),
    ("Fuer","Für"),
    ("fuer","für"),
    ("gross","groß"),
    ("Strasse","Straße"),
    ("strasse","straße"),
    ("gemaess","gemäß"),
    ("Massnahme","Maßnahme"),
    ("Huelle","Hülle"),
    ("huelle","hülle"),
    ("Aenderung","Änderung"),
    ("Gauss","Gauß"),
]

# Diese Zeichenfolgen sind technische Bezeichner und werden vorher maskiert.
GESCHUETZT = [
    # CSS-Klassen und Element-IDs
    "tabhuelle","planhuelle","plancanvas","planstatus","planleiste","kopflogo","fussbild",
    "kopfbild","primaer","gruen","huelle",
    # Aktionsnamen
    "planMassstab","planPolygon","planWaehlen","planZurueck","planUebernehmen",
    "planAlleUebernehmen","planAnsehen","planPolyWeg","planDatei",
    "schichtUebernehmen","schichtAbbrechen","schichtEdit","schichtNeu","schichtWeg",
    "kiUebernehmen","kiAuslesen","kiEinstellungen","kiVerwerfen","kiAlle","kiraum",
    "klimaUebernehmen","geschossKopieren","raumBauteile","raumNeu","raumWeg","raumZu",
    "einheitNeu","einheitWeg","zoneNeu","zoneWeg","zoneBtNeu","zoneBtWeg",
    "bauteilNeu","bauteilWeg","bauteilAusVorlage","rbtNeu","rbtWeg","vorlagenwahl",
    # Datenschluessel und Aufzaehlungswerte
    "aussen","erdreich","raeume","quelle","geschoss","strasse","massgebend","flaeche",
    "uebergang","bauteiltypen","zonen","phi_gebaeude","phi_raeume_summe","phi_T_gebaeude",
    "phi_V_gebaeude","phi_RH_gebaeude","je_we","je_geschoss","A_gesamt","V_gesamt",
    "wand_aussen","wand_unbeheizt","decke_unbeheizt","kellerdecke","dach","boden",
    "kueche","buero","lager_beheizt","treppenhaus","werkstatt","verkauf","flur",
    "haustuer_alt","haustuer_neu","innentuer","fenster_3fach","fenster_2fach_wsv",
    "fenster_2fach_alt","fenster_einfach","ziegel_vormauer","ziegel_voll","putz_kalkgips",
    "putz_aussen","holzfaser","zellulose","porenbeton","gipskarton","estrich",
    "aw_zweischalig_kern","aw_massiv_wdvs","aw_bestand_massiv","dach_zwischensparren",
    "ogd_einblas","kd_unterseitig","bodenplatte","werke_hl_standort","werke_hl_endpunkt",
    "maelzerstr59","x-werke-code","theta_e_m","theta_e","theta_fest","theta_i","theta_j",
    "n_exponiert","grenzt_an","kat_default","typ_id","zuschlag_grund","ki_herkunft",
    "plan_umfang","plan_kanten","f_RH","n_min","n50","delta_u_wb","g_w","f_g1","f_g2",
    "rho_c","epsilon","schichten","lambda","MASSBEZUG",
]

def ersetze_datei(pfad):
    s = open(pfad, encoding="utf-8").read()
    original = s
    # 1 maskieren
    marken = {}
    for i, g in enumerate(sorted(GESCHUETZT, key=len, reverse=True)):
        marke = "\x01M%03d\x02" % i
        if g in s:
            marken[marke] = g
            s = s.replace(g, marke)
    # 2 ersetzen
    for alt, neu in WOERTER:
        s = s.replace(alt, neu)
    # 3 demaskieren
    for marke, g in marken.items():
        s = s.replace(marke, g)
    if s != original:
        open(pfad, "w", encoding="utf-8").write(s)
        return True
    return False

if __name__ == "__main__":
    dateien = sys.argv[1:]
    n = 0
    for d in dateien:
        if ersetze_datei(d):
            print("  geändert:", d)
            n += 1
    print(f"{n} von {len(dateien)} Dateien geändert.")
